version: '3'
services:
  app:
    build:
      dockerfile: test.dockerfile
      context: .
    image: guilhermeroque/auth-service-test
    environment:
      - DB_URL=mongodb://mongo/
      - DB_NAME=auth-service
      - DB_USERNAME=lorawanMgnt-admin
      - DB_PASSWORD=lorawanMgnt-admin
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:5000
      - ACCESS_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - REFRESH_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src:/root/src
    ports:
      - 5000:3000
    depends_on:
      - mongo
    networks:
      - test-network

  mongo:
    image: mongo:5.0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lorawanMgnt-admin
      - MONGO_INITDB_ROOT_PASSWORD=lorawanMgnt-admin
    ports:
      - "27017:27017"
    networks:
      - test-network

  redis: 
    image: redis:7.0.4
    ports:
      - "6379:6379"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge