name: learn-github-actions
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:17-alpine3.14
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: "myUserAdmin"
          MONGO_INITDB_ROOT_PASSWORD: "password"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test

        env:
          GEN_SECRET: "45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0"
          TOKEN_EXPIRATION_TIME: "15m"
          DB_URL: "mongodb://mongo/"
          DB_NAME: "auth-service"
          DB_USERNAME: "myUserAdmin"
          DB_PASSWORD: "password"
          DB_HOST: "mongo"
          SERVER_PORT: 3000
          PRIVATE_KEY: "private.key"
          PUBLIC_KEY: "public.pem"